export const vocabularies = {
  ja: {
    "Account recovery requires verified contact information":
      "あかうんとのふっきゅうにはかくにんずみのれんらくさきがひつようです",
    "Back to Sign In": "さいんいんにもどる",
    "Change Password": "ぱすわーどをかえる",
    Changing: "へんこうちゅう",
    Code: "こーど",
    "Confirm Password": "ぱすわーどのかくにん",
    "Confirm Sign Up": "とうろくする",
    "Confirm SMS Code": "えすえむえすこーどをかくにん",
    "Confirm TOTP Code": "TOTP こーどをかくにん",
    Confirm: "かくてい",
    "Confirmation Code": "かくにんこーど",
    Confirming: "かくにんちゅう",
    "Create a new account": "あたらしいあかうんとをつくる",
    "Create Account": "あかうんとをつくる",
    "Creating Account": "あかうんとのさくせいちゅう",
    "Dismiss alert": "あらーとをとじる",
    Email: "めーるあどれす",
    "Enter your code": "こーどをにゅうりょく",
    "Enter your Email": "めーるあどれすをにゅうりょく",
    "Enter your email": "めーるあどれすをにゅうりょく",
    "Enter your phone number": "でんわばんごうをにゅうりょく",
    "Enter your username": "ゆーざーめいをにゅうりょく",
    "Enter your Username": "ゆーざーめいをにゅうりょく",
    "Forgot your password?": "ぱすわーどをわすれましたか？",
    "Hide password": "ぱすわーどをひひょうじ",
    "It may take a minute to arrive":
      "とうちゃくするまでにいっぷんかかることがあります",
    Loading: "ろーどちゅう",
    "New password": "あたらしいぱすわーど",
    or: "または",
    Password: "ぱすわーど",
    "Phone Number": "でんわばんごう",
    "Resend Code": "こーどをさいそうしん",
    "Reset your Password": "ぱすわーどをりせっと",
    "Reset your password": "ぱすわーどをりせっとする",
    "Send code": "こーどをそうしん",
    "Send Code": "こーどをそうしん",
    Sending: "そうしんちゅう",
    "Setup TOTP": "TOTP をせっとあっぷ",
    "Show password": "ぱすわーどをひょうじ",
    "Sign in to your account": "あかうんとにさいんいん",
    "Sign In with Amazon": "あまぞんでさいんいん",
    "Sign In with Apple": "あっぷるでさいんいん",
    "Sign In with Facebook": "ふぇいすぶっくでさいんいん",
    "Sign In with Google": "ぐーぐるでさいんいん",
    "Sign In": "さいんいん",
    "Sign in": "さいんいん",
    "Signing in": "さいんいんちゅう",
    Skip: "すきっぷ",
    Submit: "そうしん",
    Submitting: "そうしんちゅう",
    Username: "ゆーざーめい",
    "Verify Contact": "れんらくさきをかくにん",
    Verify: "かくにん",
    "We Sent A Code": "こーどをそうしんしました",
    "We Texted You": "てきすとをそうしんしました",
    "Your code is on the way. To log in, enter the code we sent you":
      "こーどがむかっています。ろぐいんするには、そうしんしたこーどをにゅうりょくしてください",
    "An account with the given email already exists.":
      "にゅうりょくされためーるあどれすのあかうんとがすでにそんざいします",
    "Confirm a Code": "こーどをかくにん",
    "Confirm Sign In": "さいんいんする",
    "Create account": "あかうんとをつくる",
    "Enter your password": "ぱすわーどをにゅうりょく",
    "Enter your Password": "ぱすわーどをにゅうりょく",
    "Please confirm your Password": "ぱすわーどをかくにんしてください",
    "Forgot Password": "ぱすわーどをわすれた",
    "Have an account? ": "あかうんとをもっていますか？",
    "Incorrect username or password": "ゆーざーめいかぱすわーどがちがいます",
    "Invalid password format": "ぱすわーどのけいしきがむこうです",
    "Invalid phone number format":
      "ふせいなでんわばんごうのけいしきです。\n+12345678900 のけいしきでにゅうりょくしてください",
    "It may take a minute to arrive.":
      "こーどをじゅしんするまですうふんかかるばあいがあります。",
    "Lost your code? ": "こーどをなくしましたか？",
    "New Password": "あたらしいぱすわーど",
    "No account? ": "あかうんとがないとき",
    "Password attempts exceeded":
      "さいんいんのしこうかいすうがじょうげんにたっしました",
    "Reset password": "ぱすわーどをりせっと",
    "Reset Password": "ぱすわーどをりせっと",
    "Sign Out": "さいんあうと",
    "Sign Up": "とうろく",
    "User already exists": "すでにゆーざーがそんざいしています",
    "User does not exist": "ゆーざーがそんざいしません",
    "Username cannot be empty": "ゆーざーめいはにゅうりょくひっすうです",
    "We Emailed You": "こーどをそうしんしました",
    "Your code is on the way. To log in, enter the code we emailed to":
      "ろぐいんするには、めーるにきさいされたこーどをにゅうりょくしてください。そうしんさき:",
    "Your code is on the way. To log in, enter the code we texted to":
      "ろぐいんするには、てきすとめっせーじにきさいされたこーどをにゅうりょくしてください。そうしんさき:",
    "Auth UserPool not configured.":
      "おーすゆーざーぷーるがせっていされていません",
    "Incorrect username or password.":
      "めーるあどれすまたはぱすわーどがまちがっています。",
  },
};
